### PR TITLE
Fix visulization resources id

### PR DESCRIPTION
**Pull request by BienioM**
I noticed that graph isn't working.
The problem is with resource id, but I am not sure if my fix is correct.
After added separator `/` graph starts working, but maybe the problem is somewhere inside `TemplateParser`.

### CODE REVIEW

**Comment by kamil-mrzyglod** [comment]
Could you post a template, which causes and error?

**Comment by BienioM** [comment]
[https://github.com/Azure/azure-quickstart-templates/blob/master/101-vm-multiple-data-disk/azuredeploy.json](url)

**Comment by kamil-mrzyglod** [comment]
Unfortunately this change breaks other templates, where dependencies are built using following syntax:
`
[resourceId('Microsoft.Network/publicIPAddresses', variables('publicIPAddressName'))]
`

where in your example we have
`
[concat('Microsoft.Network/publicIPAddresses/', variables('publicIPAddressName'))]
`

the real problem is how we treat `resourceId` function(which will be just "wiped out"). Maybe some change in this area would help. For know unfortunately this PR won't help.

**Comment by BienioM** [comment]
Ok, understand now.

**Pull request closed without merging**
